swagger: "2.0"
info:
  description: "This is a product for MoocTest. You can find more about MoocTest at [mooctest.net](mooctest.net)."
  version: "1.0.0"
  title: "MoocTest Data Assessment - customized for civil judgment document"
  termsOfService: "No TOS available"
  contact:
    email: "161250002@smail.nju.edu.cn"
  license:
    name: "Closed Source"
host: "localhost:5000"
basePath: "/"
tags:
- name: "writ"
  description: "所有与文书相关的接口."
- name: "writ-report"
  description: "所有单篇文书相关的接口"
- name: "task-report"
  description: "所有任务总结报告相关的接口"
schemes:
- "https"
- "http"
paths:
  /writ:
    post:
      tags:
      - writ
      summary: 文件上传、图片上传
      operationId: uploadWrit
      consumes:
      - multipart/form-data
      parameters:
      - name: file
        in: formData
        type: file
      responses:
        200:
          description: 文件上传成功
          schema:
            type: array
            items:
              type:
                string
        500:
          description: 服务器内部出错
          schema:
            type: string
    get:
      tags:
      - writ
      summary: 获取文件列表
      operationId: getWrit
      parameters:
      - name: name
        description: 文书名的一部分，如果查询字段为空，为全匹配
        in: query
        type: string
        required: false
      - name: date
        description: 文书日期的一部分，如果查询字段为空，为全匹配
        in: query
        type: string
        format: date
        required: false
      responses:
        200:
          description: 正常查询
          schema:
            type: array
            items:
              $ref: '#/definitions/writ'
        



definitions:
  writ:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      date:
        type: string
        format: date
      length:
        type: integer
        format: int32
      status:
        $ref: '#/definitions/writ-satus'
  writ-satus:
    type: string
    enum: [untested, waiting, onging, finished, wrong-format, exception]