swagger: "2.0"
info:
  description: This is a product for MoocTest. You can find more about MoocTest at [mooctest.net](http://mooctest.net).
  version: 1.0.0
  title: MoocTest Data Assessment - customized for civil judgment document
  termsOfService: No TOS available
  contact:
    email: 161250002@smail.nju.edu.cn
  license:
    name: Closed Source
host: localhost:5000
basePath: /
tags:
- name: writ
  description: 所有与文书相关的接口.
- name: writ-report
  description: 所有单篇文书相关的接口
- name: task-report
  description: 所有任务总结报告相关的接口
schemes:
- https
- http
paths:
  /writ:
    post:
      tags:
      - writ
      summary: 文件上传、图片上传
      operationId: uploadWrit
      consumes:
      - multipart/form-data
      parameters:
      - name: file
        in: formData
        type: file
      responses:
        200:
          description: 文件上传成功
          schema:
            type: array
            items:
              type:
                string
        500:
          description: 服务器内部出错
          schema:
            type: string
    get:
      tags:
      - writ
      summary: 根据文书名或时间获取文件列表
      operationId: getWrit
      parameters:
      - name: name
        description: 文书名的一部分，如果查询字段为空，为全匹配，使用like检索
        in: query
        type: string
        required: false
      - name: startTime
        description: 起始时间（晚于）
        in: query
        type: integer
        format: int64
        required: false
      - name: endTime
        description: 结束时间（早于）
        in: query
        type: integer
        format: int64
        required: false
      responses:
        200:
          description: 正常查询
          schema:
            type: array
            items:
              $ref: '#/definitions/writ'

  /writ-report/{writ-id}:
    get:
      tags:
      - 'writ-report'
      summary: 拿取报告。由于一篇文书只有一篇报告，这里用文书id拿去报告。
      operationId: getWritReport
      parameters:
      - name: 'writ-id'
        required: true
        description: 文书的id
        type: integer
        format: int64
        minimum: 1
        in: path
      responses:
        200:
          description: 查到对应报告

  /task-report/{task-id}:
    get:
      tags:
      - 'task-report'
      summary: 拿取总体报告
      operationId: getTaskReport
      parameters:
      - name: 'task-id'
        required: true
        description: 任务的id
        type: integer
        format: int64
        minimum: 1
        in: path
      responses:
        200:
          description: 查到对应报告


definitions:
  writ-status:
    type: string
    description: 文书当前所处的状态，分别是未检测，等待检测，检测中，检测完成，格式错误，意外中止
    enum: [untested, waiting, onging, finished, wrong, accident]
  writ:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: 文书的id
      name:
        type: string
        description: 文书的文件名
      time:
        type: integer
        format: int64
        description: 时间戳，从1970年1月1日开始的毫秒数，可以是负数
      length:
        type: integer
        format: int32
        description: 文书的长度
      status:
        $ref: '#/definitions/writ-status'





